name: Check Bash Scripts

on:
  pull_request:

jobs:
  lint-bash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Find and Lint All Bash Scripts
        run: |
          # Find all .sh files and run shellcheck on each
          find . -name "*.sh" -print0 | xargs -0 shellcheck
